development:
  adapter: postgresql
  encoding: unicode
  database: pencil_case_development
  pool: 5
  username: isaacjanzen

test:
  adapter: postgresql
  encoding: unicode
  database: pencil_case_test
  pool: 5
  username: isaacjanzen
